version: 2
jobs:
  build:
    working_directory: ~/app

    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2

    steps:
    - checkout

    - restore_cache:
        key: app-{{ checksum "src/IssueML/IssueML.csproj" }}

    - run: |
        dotnet tool install -g cake.tool
    - run:
        name: Build and publish
        command: |
          ~/.dotnet/tools/dotnet-cake -target=Publish
    - save_cache:
        paths:
        - ~/.m2
        key: app-{{ checksum "src/IssueML/IssueML.csproj" }}

    - persist_to_workspace:
          root: .
          paths:
            - .publish
            - Dockerfile
            - docker-compose.yml

  build-image:
    machine: true

    steps:
      - attach_workspace:
          at: .

      - run: |
          image="issue-tagging"
          version="0.1.0"
          docker login -u wk -p "${DOCKER_PASSWORD}" repo.treescale.com
          docker build -t ${image}:latest .
          docker tag  ${image}:latest wearetherock/${image}:${version}
          docker tag  ${image}:latest wearetherock/${image}:latest
          docker push wearetherock/${image}:${version}
          docker push wearetherock/${image}:latest
workflows:
  version: 2

  main:
    jobs:
      - build
      - build-image:
          requires:
            - build